# Generated by Django 4.0 on 2022-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banners')),
                ('promo_title', models.CharField(blank=True, max_length=100)),
                ('promo_subtitle', models.CharField(blank=True, max_length=100)),
                ('promo_offer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Banners lower',
            },
        ),
        migrations.CreateModel(
            name='BannerMiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banners')),
                ('promo_title', models.CharField(blank=True, max_length=100)),
                ('promo_subtitle', models.CharField(blank=True, max_length=100)),
                ('promo_offer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Banners middle',
            },
        ),
        migrations.CreateModel(
            name='BannerTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banners')),
                ('promo_title', models.CharField(blank=True, max_length=100)),
                ('promo_subtitle', models.CharField(blank=True, max_length=100)),
                ('promo_offer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Banners top',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/sliders')),
                ('discount_deal', models.CharField(choices=[('HOT DEALS', 'Hot Deals'), ('NEW ARRIVALS', 'New Arrivals'), ('NEW DEALS', 'New Deals')], max_length=100)),
                ('sale', models.IntegerField()),
                ('brand_name', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
