# Generated by Django 4.0 on 2022-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bannerlower_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/')),
                ('promo_title', models.CharField(blank=True, max_length=100)),
                ('promo_offer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
    ]
