# Generated by Django 4.0 on 2022-02-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_features_image_features_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/brands')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
